services:
  start:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./startDemoProJ:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata: